.PHONY: all say_hello generate clean

all: hello say_hello generate

var = hello_k8s

hello:
	@echo ${var}


say_hello:                       # target
	@echo "Hello World"      # recipe


generate:
	@echo "creating empty text files..."
	touch file-1.txt


clean:
	@echo "Cleaning up..."
	rm *.txt



