# foo = ok
bar =
foo = ${bar}
all:
# # conditional if-else
# ifeq ($(foo),ok)
# 	@echo "foo equals ok"
# else
# 	@echo "nope"
# endif

#check a variable is defined
ifdef foo
	@echo "foo is defined"
endif
#ifdef bar
# 	echo "bar is defined"
# endif

